# Generated by Django 5.1.15 on 2026-04-09 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.CharField(max_length=300)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('llena', 'Llena'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
                ('codigo_acceso', models.CharField(max_length=10, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fiesta',
                'verbose_name_plural': 'Fiestas',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('solicitado_en', models.DateTimeField(auto_now_add=True)),
                ('codigo_acceso', models.CharField(max_length=10)),
                ('fiesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiestas.fiesta')),
            ],
            options={
                'ordering': ['solicitado_en'],
                'unique_together': {('fiesta', 'alias')},
            },
        ),
    ]
